name: CI

on:
  # Run on all pull requests and all pushes to master
  push:
    branches: [ master ]
  pull_request:

  # Allow running this workflow manually
  workflow_dispatch:

env:
  # Set defines for builds/tests
  DEFINES: "LOG_LEVEL_VERBOSITY=LOG_LEVEL_WARN"

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup directories
        run: |
          # create directory that will be on the PATH
          mkdir -p ~/.local/bin
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          mkdir -p ~/source
     
      - uses: actions/cache@v2
        id: cache-gcc
        with:
          path: /var/cache/apt/apt-fast/gcc-6_6.5.0-2ubuntu1~16.04_amd64.deb
          key: ${{ runner.os }}-gcc

      - uses: actions/cache@v2
        id: cache-clang
        with:
          path: /var/cache/apt/apt-fast/clang-5.0_1%3a5.0-3~16.04.1_amd64.deb
          key: ${{ runner.os }}-clang
      
      - uses: actions/cache@v2
        id: cache-clang-format
        with:
          path: /var/cache/apt/apt-fast/clang-format-5.0_1%3a5.0-3~16.04.1_amd64.deb
          key: ${{ runner.os }}-clang-format

      - uses: actions/cache@v2
        id: cache-libc6-i386
        with:
          path: /var/cache/apt/archives/libc6-i386_2.27-3ubuntu1_amd64.deb
          key: ${{ runner.os }}-libc6-i386

      - uses: actions/cache@v2
        id: cache-linux-module
        with:
          path: /var/cache/apt/apt-fast/linux-modules-extra-4.15.0-1108-azure_4.15.0-1108.120~16.04.1_amd64.deb
          key: ${{ runner.os }}-linux-module

      - uses: actions/cache@v2
        id: cache-make
        with:
          path: /home/runner/work/firmware_xiv/firmware_xiv/make-4.1
          key: ${{ runner.os }}-make

      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - uses: actions/cache@v2
        id: cache-arm
        with:
          path: /tmp/tmp-13551GHF3OobAX4iW/gcc-6-2017-q2/bin
          key: ${{ runner.os }}-arm
      
      - name: Add repo and update
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update

      - name: Install gcc  
        if: steps.cache-gcc.outputs.cache-hit != 'true'
        run: sudo apt-fast -y install gcc-6

      - name: Install clang
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: sudo apt-fast -y install clang-5.0

      - name: Install clang-format
        if: steps.cache-clang-format.outputs.cache-hit != 'true'
        run: sudo apt-fast -y install clang-format-5.0

      - name: Install libc6-i386
        if: steps.cache-libc6-i386.outputs.cache-hit != 'true'
        run: sudo apt-fast -y install libc6-i386

        # for vcan module
      - name: Install linux modules
        if: steps.cache-linux-module.outputs.cache-hit != 'true'
        run: sudo apt-fast -y install linux-modules-extra-$(uname -r)

      - name: Which gcc, clang, clang-format
        run: |
          ln -sf `which gcc-6` ~/.local/bin/gcc
          ln -sf `which clang-5.0` ~/.local/bin/clang
          ln -sf `which clang-format-5.0` ~/.local/bin/clang-format
  
      - if: steps.cache-arm.outputs.cache-hit != 'true'
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '6-2017-q2'

      - name: Install GNU Make 4.1
        env:
          MAKE_PATH: make-4.1
          MAKE_ARCHIVE_PATH: make-4.1.tar.gz
          MAKE_URL: http://ftp.gnu.org/gnu/make/make-4.1.tar.gz
        if: steps.cache-make.outputs.cache-hit != 'true'
        run: |
          wget -nv $MAKE_URL
          tar xvf $MAKE_ARCHIVE_PATH
          cd $MAKE_PATH
          ./configure --prefix=${HOME}/.local
          make
          make install
          cd ..
          rm -rf $MAKE_PATH

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python tooling
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip install --user pylint
          pip install --user autopep8
          # Install dependencies from all requirements.txt in the repo
          make install_requirements

      - name: Force PATH to update
        run: hash -r

      - name: Print versions of everything
        run: |
          arm-none-eabi-gcc --version
          arm-none-eabi-objcopy --version
          arm-none-eabi-objdump --version
          arm-none-eabi-size --version
          arm-none-eabi-gcc-ar --version
          arm-none-eabi-gdb --version
          gcc --version
          make --version
          clang --version
          clang-format --version
          pylint --version
          autopep8 --version

      - name: Format
        run: |
          make test_format

      - name: Lint
          make lint

      - name: Pylint
          make pylint

      - name: Build stm32f0xx
        run: |
          make build_all PLATFORM=stm32f0xx DEFINES="${DEFINES}"
          make clean

      - name: Build x86
        run: |
          make build_all PLATFORM=x86 DEFINE="${DEFINES}"

      - name: Test x86
        run: |
          make test_all PLATFORM=x86 DEFINE="${DEFINES}"
          
      - name: Pytest
        run: |
          make pytest_all

      - name: Build x86 with clang
        run: |
          make build_all PLATFORM=x86 COMPILER=clang DEFINE="${DEFINES}"
