name: Misra-CI

on:
  # Run on all pull requests and all pushes to master
  push:
    branches: [master]
  pull_request:

  # Allow running this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-21.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2

      - name: Setup directories
        run: |
          # create directory that will be on the PATH
          mkdir -p ~/.local/bin
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          mkdir -p ~/source

      - name: Cppcheck MISRA-C Compilence
        run: |
          sudo apt-get install cppcheck
          cppcheck --addon=misra.py projects --cppcheck-build-dir=build
